### PR TITLE
Detect iTerm2 and Terminal.app by DA2 (Secondary Device Attributes)

### PR DESCRIPTION
**Pull request by yoichi**
I try to solve https://github.com/mattn/longcat/issues/27
But sometime it fails on iTerm2

スクリーンショット 2020-07-15 21 10 07

### CODE REVIEW

**Comment by yoichi** [comment]
As far as I've tried, the failures seem to only occur on macOS.

with debug print:
```
diff --git a/main.go b/main.go
index 8da2fdf..9fe7452 100644
--- a/main.go
+++ b/main.go
@@ -197,6 +197,7 @@ func checkIterm() bool {
        if err != nil {
                return false
        }
+       fmt.Printf("checkIterm: %v", b[:n])
        return string(b[:n]) == "\x1b[>0;95;0c" // iTerm2 version 3
 }

@@ -217,6 +218,7 @@ func checkTerminalApp() bool {
        if err != nil {
                return false
        }
+       fmt.Printf("checkTerminalApp: %v", b[:n])
        return string(b[:n]) == "\x1b[>1;95;0c" // Terminal.app
 }

@@ -240,6 +242,7 @@ func checkSixel() bool {
        if err != nil {
                return false
        }
+       fmt.Printf("checkSixel: %v", b[:n])
        var supportedTerminals = []string{
                "\x1b[?62;", // VT240
                "\x1b[?63;", // wsltty
```

on macOS on ITerm2:
スクリーンショット 2020-07-16 7 02 58

on Linux (docker) on ubuntu, connected by ssh from macOS iTerm2:
スクリーンショット 2020-07-16 7 04 51

**Comment by yoichi** [comment]
I've reproduced the problem on Linux (ubuntu 18.04) too.
There seems to be some problem regardless of the execution environment...

**Comment by yoichi** [comment]
I think the cause of failure is that the read operation is invoked before the terminal response is written.
I couldn't find a good way to deal with it, so I decided to put a sleep.

I've confirmed the problem is not reproduced on my environments:

* macOS and Terminal.app with "unset TERM_PROGRAM"
* macOS and iTerm2 with "unset TERM_PROGRAM"

**Comment by mattn** [comment]
Thank you!

**Pull request merged**
